# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://seonwookkim.github.io/
title: Seonwook's page
email: 21700107@handong.edu
author: SEON-WOOK KIM
description: 'Computer Engineering'
copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/kso4206/
  - title: github
    url: https://github.com/seonwookkim
  - title: instagram
    url: https://www.instagram.com/seonwock/
